const config = {
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  DATABASE_CONNECTION_STRING: process.env.DATABASE_CONNECTION_STRING,
  GEO_API_TOKEN: process.env.NEXT_PUBLIC_GEO_API_TOKEN,
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
}

export default config
